/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in local development and committed here so CI typecheck has the expected ambient declarations.
